version: '3.1'

services:

  go:
    container_name: go
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    restart: always
    ports: 
      - 0.0.0.0:80:8080
